import type { NextPage } from 'next';
import styled from 'styled-components';

import Head from 'next/head';
import HomeBanner from 'src/components/Home/HomeBanner';
import AboutOtterSection from 'src/components/Home/AboutOtterSection';
import ImageContentSections from 'src/components/Home/ImageContentSections';
import GetStartedSection from 'src/components/Home/GetStartedSection';
import JoinCommunitySection from "src/components/Home/JoinCommunitySection";

const Container = styled.div`
  background-color: ${(props) => props.theme.colors.common.white};
  position: relative;
  overflow: hidden;
`;

const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HomeBanner />
        <AboutOtterSection />
        <ImageContentSections />
        <GetStartedSection />
        <JoinCommunitySection />
      </main>
    </Container>
  )
}

export default Home;
